apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: luxstudio-ingress
  namespace: saturn
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  rules:
  - host: studio.luxoria.bluepelicansoft.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: luxstudio-service
            port:
              number: 80
  tls:
  - hosts:
    - studio.luxoria.bluepelicansoft.com
    secretName: luxstudio-saturn-luxoria