# MinIO Service
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: saturn
spec:
  selector:
    app: minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001

---

# LuxStudio App Service
apiVersion: v1
kind: Service
metadata:
  name: luxstudio-service
  namespace: saturn
spec:
  selector:
    app: luxstudio-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
