version: 2.1

jobs:
  build-local:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build LuxAPI Image
          command: |
            docker build -t luxoria/luxapi:local -f LuxStudio/LuxAPI/LuxAPI/Dockerfile LuxStudio/LuxAPI

      - run:
          name: Build LuxStudio Image
          command: |
            docker build -t luxoria/luxstudio:local -f LuxStudio/portal/Dockerfile LuxStudio/portal

workflows:
  version: 2
  build:
    jobs:
      - build-local
