version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set Image Tag
          command: |
            DATE_TAG=$(date +%Y%m%d)
            COUNT=$(git rev-list --count HEAD)
            echo "export IMAGE_TAG=${DATE_TAG}.${COUNT}" >> $BASH_ENV
            echo "Image tag: ${DATE_TAG}.${COUNT}"
      - run:
          name: Docker Login
          command: |
            echo "${DOCKERHUB_PASS}" | docker login --username "${DOCKERHUB_USER}" --password-stdin
      - run:
          name: Build & Push LuxAPI
          command: |
            source $BASH_ENV
            docker build -t luxoria/luxapi:$IMAGE_TAG -f LuxStudio/LuxAPI/LuxAPI/Dockerfile LuxStudio/LuxAPI
            docker push luxoria/luxapi:$IMAGE_TAG
      - run:
          name: Build & Push LuxStudio
          command: |
            source $BASH_ENV
            docker build -t luxoria/luxstudio:$IMAGE_TAG -f LuxStudio/portal/Dockerfile LuxStudio/portal
            docker push luxoria/luxstudio:$IMAGE_TAG

  deploy-to-pluto:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Deploy to Pluto
          command: echo "Deploying to Pluto"

  deploy-to-saturn:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Deploy to Saturn
          command: echo "Deploying to Saturn"

workflows:
  version: 2
  manual-deploy:
    jobs:
      - build-and-push:
          context: Luxoria
      - approve-deploy-to-pluto:
          type: approval
          requires:
            - build-and-push
      - deploy-to-pluto:
          requires:
            - approve-deploy-to-pluto
      - deploy-to-saturn:
          requires:
            - deploy-to-pluto
