apiVersion: apps/v1
kind: Deployment
metadata:
  name: luxapi-deployment
spec:
  template:
    spec:
      containers:
        - name: luxapi-container
          image: luxoria/luxapi
          imagePullPolicy: Always
          env:
          - name: URI__FrontEnd
            value: https://studio.pluto.luxoria.bluepelicansoft.com
          - name: URI__Backend
            value: https://api.studio.pluto.luxoria.bluepelicansoft.com
          
          