apiVersion: apps/v1
kind: Deployment
metadata:
  name: luxstudio-deployment
spec:
  template:
    spec:
      containers:
        - name: luxstudio-container
          image: luxoria/luxstudio
          imagePullPolicy: Always
          env:
            - name: NEXT_PUBLIC_API_URL
              value: https://api.studio.pluto.luxoria.bluepelicansoft.com/api
            - name: NEXT_PUBLIC_HCAPTCHA_SITEKEY
              value: 3406257c-d7d0-4ca2-93ec-dc3cf6346ac4
            - name: NEXT_PUBLIC_SIGNALR_URL
              value: https://api.studio.pluto.luxoria.bluepelicansoft.com/

# NEXT_PUBLIC_HCAPTCHA_SITEKEY variable is visible & not obstructed because it is the public key and not the private one.