apiVersion: apps/v1
kind: Deployment
metadata:
  name: luxstudio-deployment
spec:
  template:
    spec:
      containers:
        - name: luxstudio-container
          image: luxoria/luxstudio:dev
          imagePullPolicy: Always
          env:
            - name: API_URL
              value: https://api.studio.luxoria.bluepelicansoft.com