trigger:
  branches:
    include:
      - main
      - develop
      - feature/luxapi/deploy-azuredevops

variables:
  dockerHubService: DockerHubLuxoria
  dockerHubNamespace: luxoria
  imageTag: $(Build.BuildNumber)

pool:
  vmImage: ubuntu-latest

stages:
- stage: BuildAndPush
  displayName: Deploy LuxAPI and LuxStudio
  jobs:
  - job: DockerBuildPush
    displayName: Build Images
    steps:
    - checkout: self

    - task: Docker@2
      displayName: Build/Publish LuxAPI
      inputs:
        containerRegistry: $(dockerHubService)
        repository: $(dockerHubNamespace)/luxapi
        command: buildAndPush
        Dockerfile: LuxStudio/LuxAPI/LuxAPI/Dockerfile
        buildContext: LuxStudio/LuxAPI
        tags: |
          $(Build.BuildNumber)

    - task: Docker@2
      displayName: Build/Publish LuxStudio
      inputs:
        containerRegistry: $(dockerHubService)
        repository: $(dockerHubNamespace)/luxstudio
        command: buildAndPush
        Dockerfile: LuxStudio/portal/Dockerfile
        buildContext: LuxStudio/portal
        tags: |
          $(Build.BuildNumber)

# if main branch, assign created image to latest
