trigger:
  branches:
    include:
      - main
      - develop
      - feature/luxapi/deploy-azuredevops

variables:
  dockerHubService: DockerHubLuxoria
  dockerHubNamespace: luxoria
  imageTag: $(Build.SourceBranchName)  # develop or main

pool:
  vmImage: ubuntu-latest

stages:
- stage: BuildAndPush
  displayName: Build & Push to Docker Hub
  jobs:
  - job: DockerBuildPush
    displayName: Docker Build & Push
    steps:
    - checkout: self

    - task: Docker@2
      displayName: Build and Push luxapi
      inputs:
        containerRegistry: $(dockerHubService)
        repository: $(dockerHubNamespace)/luxapi
        command: buildAndPush
        Dockerfile: LuxAPI/Dockerfile
        buildContext: LuxStudio/LuxAPI
        tags: |
          $(imageTag)

    - task: Docker@2
      displayName: Build and Push luxstudio
      inputs:
        containerRegistry: $(dockerHubService)
        repository: $(dockerHubNamespace)/luxstudio
        command: buildAndPush
        Dockerfile: Dockerfile
        buildContext: LuxStudio/portal
        tags: |
          $(imageTag)
