using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LuxAPI.Models
{
    /// <summary>
    /// Represents an authorization code used in the OAuth 2.0 flow.
    /// This code is generated during user authentication and exchanged for an access token.
    /// </summary>
    [Table("AuthorizationCodes")]
    public class AuthorizationCode
    {
        /// <summary>
        /// Unique identifier for the authorization code record.
        /// Automatically generated by the database.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }

        /// <summary>
        /// The actual authorization code issued to the client.
        /// Limited to 100 characters.
        /// </summary>
        [Required(ErrorMessage = "Authorization code is required.")]
        [MaxLength(100, ErrorMessage = "Authorization code cannot exceed 100 characters.")]
        public required string Code { get; set; }

        /// <summary>
        /// The unique identifier of the client application that requested authorization.
        /// </summary>
        [Required(ErrorMessage = "Client ID is required.")]
        public Guid ClientId { get; set; }

        /// <summary>
        /// The unique identifier of the authenticated user.
        /// This links the authorization code to a specific user.
        /// </summary>
        [Required(ErrorMessage = "User ID is required.")]
        public Guid UserId { get; set; }

        /// <summary>
        /// The expiration date and time of the authorization code.
        /// After this time, the code is no longer valid.
        /// </summary>
        [Required(ErrorMessage = "Expiry date is required.")]
        public DateTime Expiry { get; set; }
    }
}
