using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LuxAPI.Models
{
    /// <summary>
    /// Represents a registered client application in the authentication system.
    /// Clients are authorized applications that request access to protected resources.
    /// </summary>
    [Table("Clients")]
    public class Client
    {
        /// <summary>
        /// Unique identifier for the client record.
        /// Automatically generated by the database.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }

        /// <summary>
        /// The public identifier assigned to the client application.
        /// This ID is used during authentication and authorization requests.
        /// </summary>
        [Required(ErrorMessage = "Client ID is required.")]
        public Guid ClientId { get; set; }

        /// <summary>
        /// The secret key assigned to the client application.
        /// Used for client authentication. Should be stored securely.
        /// </summary>
        [Required(ErrorMessage = "Client secret is required.")]
        [MaxLength(100, ErrorMessage = "Client secret cannot exceed 100 characters.")]
        public required string ClientSecret { get; set; }

        /// <summary>
        /// The authorized redirect URI for the client.
        /// The authentication server will only redirect to this URI after authorization.
        /// </summary>
        [Required(ErrorMessage = "Redirect URI is required.")]
        [MaxLength(200, ErrorMessage = "Redirect URI cannot exceed 200 characters.")]
        public required string RedirectUri { get; set; }
    }
}
