using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LuxAPI.Models
{
    /// <summary>
    /// Represents a refresh token used for renewing access tokens.
    /// Refresh tokens allow users to stay authenticated without re-entering credentials.
    /// </summary>
    [Table("RTokens")]
    public class RefreshToken
    {
        /// <summary>
        /// Unique identifier for the refresh token record.
        /// Automatically generated by the database.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }

        /// <summary>
        /// The refresh token string used to obtain a new access token.
        /// Stored as a TEXT type in the database to allow variable-length storage.
        /// </summary>
        [Required(ErrorMessage = "Refresh token is required.")]
        [Column(TypeName = "TEXT")]
        public string? Token { get; set; }

        /// <summary>
        /// The unique identifier of the user associated with this refresh token.
        /// Links the token to a specific user account.
        /// </summary>
        [Required(ErrorMessage = "User ID is required.")]
        public Guid UserId { get; set; }

        /// <summary>
        /// Navigation property for the related user entity.
        /// Establishes a foreign key relationship with the User table.
        /// </summary>
        [ForeignKey(nameof(UserId))]
        public User? User { get; set; } 

        /// <summary>
        /// The expiration date and time of the refresh token.
        /// Once expired, the token is no longer valid and must be replaced.
        /// </summary>
        [Required(ErrorMessage = "Expiry date is required.")]
        public DateTime Expiry { get; set; }
    }
}
