apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: luxstudio-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  rules: []  # Patched per environment
  tls: []    # Patched per environment
