version: '3.8'

services:
  luxdb:
    image: postgres:17.2-alpine3.21
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: luxoria
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - luxnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: >
      postgres -c 'hba_file=/var/lib/postgresql/data/pg_hba.conf'

  luxapi:
    build:
      context: LuxAPI
      dockerfile: LuxAPI/Dockerfile
    restart: always
    depends_on:
      - luxdb
    environment:
      - ConnectionStrings__DefaultConnection=Host=luxdb;Database=luxoria;Username=postgres;Password=password
      - JWT_SECRET=$(openssl rand -hex 32)
      - JWT_EXPIRATION=3600
      - ENVIRONMENT=SATURN
      - PORT=8080
      - Uri__FrontEnd=http://129.12.234.243:3000
      - Uri__Backend=http://129.12.234.243:5555
      - Minio__Endpoint=minio:9000
      - Minio__AccessKey=your-access-key
      - Minio__SecretKey=your-secret-key
    ports:
      - 5555:8080
    networks:
      - luxnet
  
  luxportal:
    build:
      context: portal
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - luxapi
    environment:
      - API_URL=http://129.12.234.243:5555
    ports:
      - 3000:80

volumes:
  pgdata:

networks:
  luxnet: