services:
  luxdb:
    image: postgres:17.2-alpine3.21
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - luxnet
    ports:
      - 5432:5432
    command: >
      postgres -c 'hba_file=/var/lib/postgresql/data/pg_hba.conf'
  
  luxapi:
    build:
      context: LuxAPI
      dockerfile: LuxAPI/Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:password@luxdb:5432/postgres
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRATION=3600
      - ENVIRONMENT=SATURN
      - PORT=8080
    ports:
      - 5555:8080
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - luxnet
 
volumes:
  pgdata:

networks:
  luxnet:
