name: Luxoria Standard Modules Release

on:
  push:


jobs:
  build-and-upload:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Release]
        platform: [win-x64]
    
    env:
      Solution_Name: Luxoria.App.sln
      Framework_Version: net9.0-windows10.0.26100.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
            
      # Build Luxoria.App
      - name: Build Luxoria.App
        run: dotnet build Luxoria.App/Luxoria.App.sln --no-incremental -p:PackOnBuild=false -maxcpucount:1 -c ${{ matrix.configuration }} -r ${{ matrix.platform }}

      # Build and upload LuxImport
      - name: Build LuxImport
        run: dotnet build Modules/LuxImport/LuxImport/LuxImport.csproj --no-incremental -c ${{ matrix.configuration }} -r ${{ matrix.platform }}

      - name: Upload LuxImport artifact
        uses: actions/upload-artifact@v4
        with:
          name: LuxImport-${{ matrix.platform }}
          path: Modules/LuxImport/LuxImport/bin/${{ matrix.configuration }}/${{ env.Framework_Version }}/${{ matrix.platform }}

      # Build and upload LuxFilter
      - name: Build LuxFilter
        run: dotnet build Modules/LuxFilter/LuxFilter/LuxFilter.csproj --no-incremental -c ${{ matrix.configuration }} -r ${{ matrix.platform }}

      - name: Upload LuxFilter artifact
        uses: actions/upload-artifact@v4
        with:
          name: LuxFilter-${{ matrix.platform }}
          path: Modules/LuxFilter/LuxFilter/bin/${{ matrix.configuration }}/${{ env.Framework_Version }}/${{ matrix.platform }}

      # Build and upload LuxEditor
      - name: Build LuxEditor
        run: dotnet build Modules/LuxEditor/LuxEditor/LuxEditor.csproj --no-incremental -c ${{ matrix.configuration }} -r ${{ matrix.platform }}

      - name: Upload LuxEditor artifact
        uses: actions/upload-artifact@v4
        with:
          name: LuxEditor-${{ matrix.platform }}
          path: Modules/LuxEditor/LuxEditor/bin/${{ matrix.configuration }}/${{ env.Framework_Version }}/${{ matrix.platform }}

      # Build and upload LuxExport
      - name: Build LuxExport
        run: dotnet build Modules/LuxExport/LuxExport/LuxExport.csproj --no-incremental -c ${{ matrix.configuration }} -r ${{ matrix.platform }}
      
      - name: Upload LuxExport artifact
        uses: actions/upload-artifact@v4
        with:
          name: LuxExport-${{ matrix.platform }}
          path: Modules/LuxExport/LuxExport/bin/${{ matrix.configuration }}/${{ env.Framework_Version }}/${{ matrix.platform }}