name: Luxoria Standard Modules Release

on:
  push:


jobs:
  build-and-upload:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Release]
        platform: [win-x64, win-x86, win-arm64]
    
    env:
      Solution_Name: Luxoria.App.sln
      Framework_Version: net9.0-windows10.0.26100.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
            
      # Build Luxoria.App
      - name: Build Luxoria.App
        run: |
          if ("${{ matrix.platform }}" -eq "win-x86") {
            $platformTarget = "x86"
          } elseif ("${{ matrix.platform }}" -eq "win-x64") {
            $platformTarget = "x64"
          } elseif ("${{ matrix.platform }}" -eq "win-arm64") {
            $platformTarget = "ARM64"
          } else {
            throw "Unknown platform: ${{ matrix.platform }}"
          }
          dotnet build Luxoria.App/Luxoria.App.sln --no-incremental -p:PackOnBuild=false -maxcpucount:1 -c ${{ matrix.configuration }} -r ${{ matrix.platform }} -p:PlatformTarget=$platformTarget
        shell: pwsh


      # Build and upload LuxImport
      - name: Build LuxImport
        run: dotnet publish Modules/LuxImport/LuxImport/LuxImport.csproj -c ${{ matrix.configuration }} -r ${{ matrix.platform }}

      - name: Upload LuxImport artifact
        uses: actions/upload-artifact@v4
        with:
          name: LuxImport-${{ matrix.platform }}
          path: Modules/LuxImport/LuxImport/bin/${{ matrix.configuration }}/${{ env.Framework_Version }}/${{ matrix.platform }}
      
      # Rename publish/LuxImport.dll to publish/LuxImport.Lux.dll
      - name: Rename LuxImport.dll
        run: |
          $sourcePath = "Modules/LuxImport/LuxImport/bin/${{ matrix.configuration }}/${{ env.Framework_Version }}/${{ matrix.platform }}/LuxImport.dll"
          $destinationPath = "Modules/LuxImport/LuxImport/bin/${{ matrix.configuration }}/${{ env.Framework_Version }}/${{ matrix.platform }}/LuxImport.Lux.dll"
          Rename-Item -Path $sourcePath -NewName $destinationPath
        shell: pwsh

      # Build and upload LuxFilter
      - name: Build LuxFilter
        run: dotnet publish Modules/LuxFilter/LuxFilter/LuxFilter.csproj -c ${{ matrix.configuration }} -r ${{ matrix.platform }}
      
      # Rename publish/LuxFilter.dll to publish/LuxFilter.Lux.dll
      - name: Rename LuxFilter.dll
        run: |
          $sourcePath = "Modules/LuxFilter/LuxFilter/bin/${{ matrix.configuration }}/${{ env.Framework_Version }}/${{ matrix.platform }}/LuxFilter.dll"
          $destinationPath = "Modules/LuxFilter/LuxFilter/bin/${{ matrix.configuration }}/${{ env.Framework_Version }}/${{ matrix.platform }}/LuxFilter.Lux.dll"
          Rename-Item -Path $sourcePath -NewName $destinationPath
        shell: pwsh

      - name: Upload LuxFilter artifact
        uses: actions/upload-artifact@v4
        with:
          name: LuxFilter-${{ matrix.platform }}
          path: Modules/LuxFilter/LuxFilter/bin/${{ matrix.configuration }}/${{ env.Framework_Version }}/${{ matrix.platform }}

      # Build and upload LuxEditor
      - name: Build LuxEditor
        run: dotnet publish Modules/LuxEditor/LuxEditor/LuxEditor.csproj -c ${{ matrix.configuration }} -r ${{ matrix.platform }}
      
      # Rename publish/LuxEditor.dll to publish/LuxEditor.Lux.dll
      - name: Rename LuxEditor.dll
        run: |
          $sourcePath = "Modules/LuxEditor/LuxEditor/bin/${{ matrix.configuration }}/${{ env.Framework_Version }}/${{ matrix.platform }}/LuxEditor.dll"
          $destinationPath = "Modules/LuxEditor/LuxEditor/bin/${{ matrix.configuration }}/${{ env.Framework_Version }}/${{ matrix.platform }}/LuxEditor.Lux.dll"
          Rename-Item -Path $sourcePath -NewName $destinationPath
        shell: pwsh
      - name: Upload LuxEditor artifact
        uses: actions/upload-artifact@v4
        with:
          name: LuxEditor-${{ matrix.platform }}
          path: Modules/LuxEditor/LuxEditor/bin/${{ matrix.configuration }}/${{ env.Framework_Version }}/${{ matrix.platform }}

      # Build and upload LuxExport
      - name: Build LuxExport
        run: dotnet publish Modules/LuxExport/LuxExport/LuxExport.csproj -c ${{ matrix.configuration }} -r ${{ matrix.platform }}

      # Rename publish/LuxExport.dll to publish/LuxExport.Lux.dll
      - name: Rename LuxExport.dll
        run: |
          $sourcePath = "Modules/LuxExport/LuxExport/bin/${{ matrix.configuration }}/${{ env.Framework_Version }}/${{ matrix.platform }}/LuxExport.dll"
          $destinationPath = "Modules/LuxExport/LuxExport/bin/${{ matrix.configuration }}/${{ env.Framework_Version }}/${{ matrix.platform }}/LuxExport.Lux.dll"
          Rename-Item -Path $sourcePath -NewName $destinationPath
        shell: pwsh
      
      - name: Upload LuxExport artifact
        uses: actions/upload-artifact@v4
        with:
          name: LuxExport-${{ matrix.platform }}
          path: Modules/LuxExport/LuxExport/bin/${{ matrix.configuration }}/${{ env.Framework_Version }}/${{ matrix.platform }}