name: Luxoria Desktop App Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]

    env:
      Solution_Name: Luxoria.App.sln

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'  # Specify the .NET SDK version you are using
      
      # Restore the nugget packages
      - name: Restore LDA nuget packages
        run: dotnet restore $env:Solution_Name
        working-directory: ./Luxoria.App
      
      # Build LDA project
      - name: Build LDA project
        run: dotnet build --no-restore $env:Solution_Name --configuration $env:Configuration -r win-x64
        env:
          Configuration: ${{ matrix.configuration }}
        working-directory: ./Luxoria.App
      
      # Publish LDA project
      - name: Publish LDA project
        run: dotnet publish --no-restore $env:Solution_Name --configuration $env:Configuration --output $env:Publish_Output
        env:
          Configuration: ${{ matrix.configuration }}
          Publish_Output: ./publish
        working-directory: ./Luxoria.App