name: Upload to Luxoria Marketplace

on:
  release:
    types: [published]

jobs:
  upload-to-marketplace:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
        
      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Marketplace Manager Dependencies
        run: |
          cd tools/luxmktplacemgr
          poetry install

      - name: Upload to Marketplace
        run: |
          cd tools/luxmktplacemgr
          poetry run upload-base https://github.com/luxoriasoft/luxoria.git https://github.com/luxoriasoft/marketplace.git ${{ github.event.release.tag_name }}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
